### ISSUE TITLE
Fix failing multi-floor test case 

### ISSUE THREAD

**Issue by linuxboss182** [linuxboss182/SoftEng-2017#142] opened 2017-04-13 00:44 UTC
One of the tests are failing

**Comment by wggallati** [comment] 2017-04-17 17:25
Fun fact - the test passes in dev/master, but fails in origin/master. Looks like the problem isn't with the test but with the disparity between branches

**Comment by jirassimok** [comment] 2017-04-17 17:26
Oh; yeah. Forgot there was an issue for this. The problem was a change I made in Node that prevented connecting roomless nodes across floors.

That should be fixed now.

**Closed as completed** 2017-04-17 17:27 UTC
Labels: bug, help wanted
