### ISSUE TITLE
Fix Path drawing issue with certain search algorithm

### ISSUE THREAD

**Issue by TheodoreJBieber** [linuxboss182/SoftEng-2017#187] opened 2017-04-19 06:21 UTC
If you have a path that is drawn from one floor then another floor and back to the first floor, the path visible on the first floor will all be connected to itself. This needs to be fixed so that does not happen

**Comment by jirassimok** [comment] 2017-04-19 16:02
To solve this, UserPathController should draw the path in segments, rather than connecting all nodes on the floor in sequence.

**Comment by jirassimok** [comment] 2017-04-19 16:05
Duplicate of #177

**Closed as completed by jirassimok** 2017-04-19 16:05 UTC
Labels: bug
